### ISSUE TITLE
Please provide AppImage for download

### ISSUE THREAD

**Issue by probonopd** [deathsec/9anime#9]
On https://github.com/deathsec/9anime/blob/5533e584d2b5d563d602ca42daefce10046b5866/DeployResources/Deploy.md it says

> NineAnime Uses AppImage to port to Major Linux Distros , NineAnime is Deployed with Qt5.9.2

But the GitHub Releases page does not provide an AppImage, only a `installer-linux-x86_64.run` file. Where can the AppImage be downloaded?

**Comment by deathsec** [comment]
sure do , I used Qt Installer framework because it had some inbuilt maintanance tool but a AppImage is also sometimes handy right?... will deploy it now , But this is just alpha and the code base is not very clean!

**Comment by deathsec** [comment]
AppImage Added


|         GNU/Linux X11:penguin:|      Microsoft Windows   |                  Apple MacOSX                              | 
|-------------------------------|--------------------------|------------------------------------------------------------|
|[![Download](https://img.shields.io/badge/x86__64-DOWNLOAD-orange.svg?style=for-the-badge)](https://github.com/deathsec/9anime/releases/download/v0.0.1-alpha/nineanime-installer-linux-x86_64.run)  [![Download App Image](https://img.shields.io/badge/AppImage-DOWNLOAD-orange.svg?style=for-the-badge)](https://github.com/deathsec/9anime/releases/download/v0.0.1-alpha/NineAnime-x86_64.AppImage) | [![Download](https://img.shields.io/badge/WIN64-DOWNLOAD-brightgreen.svg?style=for-the-badge)](https://github.com/deathsec/9anime/releases/download/v0.0.1-alpha/nineanime-windows-64Bit-installer.exe) |Open a Issue , If you are interrested in Compiling Qt|

**Comment by deathsec** [comment]
I used your tool linuxdeployqt but it did'nt work well with QtWebEngine but I used a simple trick.
* Download Qt5.9.2 Pre-Built .run for linux_X11
* set Path to the Installed Pre-Built Version and use that qmake on my .pro file
* compile the release version.
* create a fresh directory and copy only the executable ( Dynamic )
* now copy **lib(Only Required Libs) , libexec , resources , plugins(only required)  and translations**
  to the fresh directory.
* it should look like this
```
lib translations  NineAnime libexec  plugins resources
```

* now create a qt.conf file inside libexec , which should have this
```
[Paths]
Prefix=..
```
* now create a qt.conf in the main directory , which should have this
```
[Paths]
Prefix=.
```
* **Also create a Startup script in the main directory** , which should have **like** this

```
#!/bin/sh
# 
# The MIT License.
# Copyright (c) 2017 The Future Shell , antonyjr(@DeathSec)
# 
# @filename    : NineAnime.sh
# @description : NineAnime Qt App Startup Shell Script , Sets Loader Path

cd "$(dirname "$0")" # Set Working Directory

LD_LIBRARY_PATH=lib
export LD_LIBRARY_PATH

# Start App
./NineAnime
```
* Now simply executing the **.sh** script will run the Qt App.

* Now pack your app with AppImage or Qt Installer Framework

**Anyways , Danke!**
